apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot-api
spec:
  rules:
    - host: bot-api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot-api-svc
                port:
                  number: 8080
