apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tock-studio
spec:
  rules:
    - host: tock-studio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot-admin-svc
                port:
                  number: 8080
